# This file was generated by GoReleaser. DO NOT EDIT.
class Sopstool < Formula
  desc "A multi-file wrapper for Mozilla sops"
  homepage "https://github.com/Ibotta/sopstool"
  version "0.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ibotta/sopstool/releases/download/v0.4.1/sopstool_darwin.tar.gz"
    sha256 "b135037bbe7f5ec2abce39d1ef629d8593cfbc5cd683a48faa4bef8e5f6dbe14"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ibotta/sopstool/releases/download/v0.4.1/sopstool_linux.tar.gz"
      sha256 "161f35bd4eb6c9db7167fd06c0a516ca4c82a30c549dfed0b4affa15e6cdf0c0"
    end
  end
  
  depends_on "sops"

  def install
    bin.install "sopstool"
  end

  test do
    system "#{bin}/sopstool version"
  end
end
