# This file was generated by GoReleaser. DO NOT EDIT.
class Sopstool < Formula
  desc "A multi-file wrapper for Mozilla sops"
  homepage "https://github.com/Ibotta/sopstool"
  url "https://github.com/Ibotta/sopstool/releases/download/v0.3.3/sopstool_darwin.tar.gz"
  version "0.3.3"
  sha256 "6e4ce46cd4e40bd896f3eada2102da6b97cd3d6503b3f40bf864dee3df850e0e"
  
  depends_on "sops"

  def install
    bin.install "sopstool"
  end

  test do
    system "#{bin}/sopstool version"
  end
end
